# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Check 
  displayName: Check Stage
  jobs:  
  - job: Check
    displayName: Code check
    
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonarcloud'
        organization: 'sonarcloud-hari'
        scannerMode: 'CLI'
        configMode: 'file'

    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'


- stage: Build 
  displayName: Docker Stage
  jobs:  
  - job: Check
    displayName: Scan check 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        command: 'build'
        Dockerfile: '**/Dockerfile'


     
