apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: pythondock 
spec: 
  selector: 
    matchLabels: 
      app: python 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: python 
    spec: 
      containers: 
      - name: python 
        image: harikrishnancs/pythondock:latest
        ports: 
        - containerPort: 5000 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: pythondock 
spec: 
  selector: 
    app: python 
  ports: 
  - protocol: TCP 
    port: 5000 
    targetPort: 5000 
  type: LoadBalancer 
