apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: pocust.azurecr.io/PythonDock:#{Build.BuildId}#
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: python
 
