apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-dock
  template:
    metadata:
      labels:
        app: python-dock
    spec:
      containers:
      - name: python-dock
        image: pocust.azurecr.io/PythonDock:#{Build.BuildId}#
        ports:
        - containerPort: 5000
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: python-dock
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: python-dock
 
